### ISSUE TITLE
Unknown installation status in managed-edition

### ISSUE THREAD

**Issue by gtwone** [contao-bootstrap/bundle#4]
Ich habe die managed-edition Version 4.4.6 und das bundle installiert. In der composer.json kam dazu:
`"minimum-stability": "dev",
    "prefer-stable": true,`

Dies führt dazu, dass der Contao Manager den Error 500 Unknown installation status wirft. Deinstalliere ich das bundle läuft er tip top. Contao selbst läuft aber stabil weiter - mit oder ohne bundle.

Server: FreeBSD 10.3 mit PHP 7.1

**Comment by dmolineus** [comment]
It seems that the contao manager runs into an memory limit resolving all dependencies. 

You could try to following setups:
 - Don't add minimum stability setting. Install every component alone force beta version `~2.0@beta` for the them:
    - `contao-bootstrap/core: ~2.0@beta`
    - `contao-bootstrap/layout: ~2.0@beta`
    - `contao-bootstrap/grid: ~2.0@beta`
    - `contao-bootstrap/form: ~2.0@beta`
    - `contao-bootstrap/navbar: ~2.0@beta`

This is possible because the you can force an unstable version in the top composer.json. The bundle seems to be not allowed to do it.
 - Instead of setting `minimum-stability` to `dev` you could set it to beta as all components reached the beta state

Additional info: The multicolumn wizard seems to be broken in the latest releases. You probably have to install menatwork/contao-multicolumnwizard as version 3.3.10.

**Comment by gtwone** [comment]
Thank you for your reply.
Without `minimum-stability` the Manager breaks even after installing `contao-bootstrap/core`
But the memory limitation is not unlikely.

**Comment by dmolineus** [comment]
> Thank you for your reply.
> Without minimum-stability the Manager breaks even after installing contao-bootstrap/core
> But the memory limitation is not unlikely.

It should'nt break if you manually set the version to `~2.0@beta` for the core and install the core before any other component.
