### ISSUE TITLE
PHP Version Composer

### ISSUE THREAD

**Issue by hypergalaktisch** [contao-bootstrap/bundle#5]
Ich erhalte folgende Meldung beim Versuch die Beta-Version über den Contao-Manager zu installieren:

`roblem 1
    - contao-bootstrap/core 2.0.0-beta1 requires php >=7.1 -> your PHP version (5.6.30) does not satisfy that requirement.
    - contao-bootstrap/bundle 2.0.0-beta1 requires contao-bootstrap/core ~2.0.0@beta -> satisfiable by contao-bootstrap/core[2.0.0-beta1].
    - Installation request for contao-bootstrap/bundle ~2.0@beta -> satisfiable by contao-bootstrap/bundle[2.0.0-beta1].`

Meine Domain läuft über CGI auf der PHP-Version 7.1, der Composer scheint allerdings die 5.6.30 zu nutzen, komme nun an der Installation nicht weiter. Es besteht die Möglichkeit meinen Server umzuziehen und auf 7.1 als globale PHP-Version umzusteigen, allerdings kann ich mir gut vorstellen, dass ich nicht der einzige mit dem Problem bin und von daher reicht eventuell ein Warnhinweis?

**Comment by dmolineus** [comment]
This is actually not related to the contao-bootstrap extension but how composer/contao manager works.

The issue is that the Contao Manager seems to use the wrong PHP version. You can configure it anyway:

- https://docs.contao.org/books/manager/de/installation-manager.html#php-binary---experten-einstellungen
 - Change the `php_cli` manually in `contao-manager/manager.json`
 - Configure the platform in the `composer.json` (https://getcomposer.org/doc/06-config.md#platform)
